version: '3.1'

services:
  api:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./API/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - ./api/app:/code/app

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db   
volumes:
  mongodb_data_container: